/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hKHBJ8ShyWe
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useContext, useState, useEffect } from "react";
import AppContext from "@/contexts/AppContext";
import useRedirect from "@/hooks/useRedirect";
export function BillDetails() {
  const mainMeterContext = useContext(AppContext);
  const { mainMeterUnit, meterUnitDifference, month, subMeterUnit, year } =
    mainMeterContext.mainMeterContext;
  useEffect(() => {
    // console.log(mainMeterUnit, meterUnitDifference, month, subMeterUnit, year);
    if (mainMeterContext?.mainMeterContext?.length === 0) {
      // eslint-disable-next-line react-hooks/rules-of-hooks
      useRedirect("/bill");
    }
    if (
      !mainMeterUnit ||
      !meterUnitDifference ||
      !month ||
      !subMeterUnit ||
      !year
    ) {
      // eslint-disable-next-line react-hooks/rules-of-hooks
      useRedirect("/bill");
    }
  }, [
    mainMeterContext,
    mainMeterUnit,
    meterUnitDifference,
    month,
    subMeterUnit,
    year,
  ]);
  const handleSubmit = (event) => {
    event.preventDefault();
    const formData = new FormData(event.target);
    const data = Object.fromEntries(formData);
    const {
      demandCharge,
      meterCharge,
      otherCharge,
      totalBill,
      usageBill,
      vatCharge,
    } = data;
    // check whether values are positive else return
    if (
      demandCharge < 0 ||
      meterCharge < 0 ||
      totalBill < 0 ||
      usageBill < 0 ||
      vatCharge < 0
    ) {
      alert("জরিমানা ব্যাতিত বাকি চার্জসমুহ অবশ্যই ধনাত্মক হতে হবে");
      return;
    }
    const totalAdditionalCharge =
      parseInt(demandCharge) +
      parseInt(meterCharge) +
      parseInt(otherCharge) +
      parseInt(vatCharge);
    // console.log(totalAdditionalCharge)
    // todo: fix err
    const perUnitCost = usageBill / mainMeterUnit;
    const mainMeterUserBill =
      perUnitCost * meterUnitDifference + totalAdditionalCharge / 2;
    const subMeterUserBill =
      perUnitCost * subMeterUnit + totalAdditionalCharge / 2;
    const realPerUnitCost = totalBill / mainMeterUnit;
    const finalUnitCost = realPerUnitCost == 0 ? perUnitCost : realPerUnitCost;
    const FinalBillData = {
      totalBill,
      usageBill,
      mainMeterUserBill,
      subMeterUserBill,
      totalAdditionalCharge,
      perUnitCost,
      finalUnitCost,
      mainMeterUnit,
      meterUnitDifference,
      month,
      subMeterUnit,
      year,
    };
    // console.log(FinalBillData);
    mainMeterContext.setMainMeterContext(FinalBillData);

    //save data to local storage with id
    const id = Date.now();
    const billData = {
      id,
      ...FinalBillData,
    };
    const billDataList = JSON.parse(localStorage.getItem("billDataList")) || [];
    billDataList.push(billData);
    localStorage.setItem("billDataList", JSON.stringify(billDataList));

    // eslint-disable-next-line react-hooks/rules-of-hooks
    useRedirect("/bill/summary");
  };
  return (
    <main className="container mx-auto p-6">
      <form
        onSubmit={handleSubmit}
        className="mb-24 space-y-8 max-w-2xl mx-auto"
      >
        <Card className="p-4 space-y-4">
          <CardHeader>
            <h2 className="text-2xl font-bold">বিদ্যুৎ ব্যবহার</h2>
          </CardHeader>
          <CardContent className="flex flex-col md:flex-row gap-4">
            <div className="w-full md:w-1/2">
              <Label htmlFor="float1">ব্যবহৃত বিদ্যুৎ (টাকা)</Label>
              <Input
                className="w-full"
                required={true}
                name="usageBill"
                id="float1"
                placeholder="0.00"
                step="0.01"
                type="number"
              />
            </div>
            <div className="w-full md:w-1/2">
              <Label htmlFor="float2">সর্বমোট ব্যবহার/কর্তন (টাকা)</Label>
              <Input
                className="w-full"
                id="float2"
                required={true}
                name="totalBill"
                placeholder="0.00"
                step="0.01"
                type="number"
              />
            </div>
          </CardContent>
        </Card>
        <Card className="p-4 space-y-4">
          <CardHeader>
            <h2 className="text-2xl font-bold">ভ্যাট/ অন্যান্য চার্জ</h2>
          </CardHeader>
          <CardContent className="flex flex-col md:flex-row gap-4">
            <div className="w-full md:w-1/2">
              <div className="w-full ">
                <Label htmlFor="float3">মিটার ভাড়া (টাকা)</Label>
                <Input
                  className="w-full"
                  id="float3"
                  required={true}
                  name="meterCharge"
                  placeholder="0.00"
                  step="0.01"
                  type="number"
                />
              </div>
              <div className="w-full">
                <Label htmlFor="float4">ডিমান্ড চার্জ (টাকা)</Label>
                <Input
                  className="w-full"
                  id="float4"
                  required={true}
                  name="demandCharge"
                  placeholder="0.00"
                  step="0.01"
                  type="number"
                />
              </div>
            </div>
            <div className="w-full md:w-1/2">
              <div className="w-full">
                <Label htmlFor="float3">ভ্যাট (টাকা)</Label>
                <Input
                  className="w-full"
                  id="float3"
                  required={true}
                  name="vatCharge"
                  placeholder="0.00"
                  step="0.01"
                  type="number"
                />
              </div>
              <div className="w-full">
                <Label htmlFor="float4">জরিমানা/ অন্যান্য</Label>
                <Input
                  className="w-full"
                  id="float4"
                  required={true}
                  name="otherCharge"
                  placeholder="0.00"
                  step="0.01"
                  type="number"
                />
              </div>
            </div>
          </CardContent>
        </Card>
        <div className="flex justify-center">
          <Button
            className="px-6 py-2 text-white bg-blue-500 rounded hover:bg-blue-600 transition-colors duration-200"
            type="submit"
          >
            জমা দিন
          </Button>
        </div>
      </form>
    </main>
  );
}
