/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hKHBJ8ShyWe
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function BillForm1() {
  return (
    <main className="container mx-auto p-6">
      <form className="mb-24 space-y-8 max-w-2xl mx-auto">
        <Card className="p-4 space-y-4">
          <CardHeader>
            <h1 className="text-2xl font-bold">Date Selection</h1>
          </CardHeader>
          <CardContent className="flex flex-col md:flex-row gap-4">
            <div className="w-full md:w-1/2">
              <Label htmlFor="month">Month</Label>
              <select className="select select-bordered w-full max-w-xs">
                <option disabled selected>
                  Select The Billing Month
                </option>
                <option>Han Solo</option>
                <option>Greedo</option>
              </select>
            </div>
            <div className="w-full md:w-1/2">
              <Label htmlFor="year">Year</Label>
              <Input
                className="w-full h-12"
                id="year"
                placeholder="Year"
                type="number"
              />
            </div>
          </CardContent>
        </Card>
        <Card className="p-4 space-y-4">
          <CardHeader>
            <h2 className="text-2xl font-bold">First Float Inputs</h2>
          </CardHeader>
          <CardContent className="flex flex-col md:flex-row gap-4">
            <div className="w-full md:w-1/2">
              <Label htmlFor="float1">First Float</Label>
              <Input
                className="w-full"
                id="float1"
                placeholder="0.00"
                step="0.01"
                type="number"
              />
            </div>
            <div className="w-full md:w-1/2">
              <Label htmlFor="float2">Second Float</Label>
              <Input
                className="w-full"
                id="float2"
                placeholder="0.00"
                step="0.01"
                type="number"
              />
            </div>
          </CardContent>
        </Card>
        <Card className="p-4 space-y-4">
          <CardHeader>
            <h2 className="text-2xl font-bold">Second Float Inputs</h2>
          </CardHeader>
          <CardContent className="flex flex-col md:flex-row gap-4">
            <div className="w-full md:w-1/2">
              <Label htmlFor="float3">Third Float</Label>
              <Input
                className="w-full"
                id="float3"
                placeholder="0.00"
                step="0.01"
                type="number"
              />
            </div>
            <div className="w-full md:w-1/2">
              <Label htmlFor="float4">Fourth Float</Label>
              <Input
                className="w-full"
                id="float4"
                placeholder="0.00"
                step="0.01"
                type="number"
              />
            </div>
          </CardContent>
        </Card>
        <div className="flex justify-center">
          <Button
            className="px-6 py-2 text-white bg-blue-500 rounded hover:bg-blue-600 transition-colors duration-200"
            type="submit"
          >
            Submit
          </Button>
        </div>
      </form>
    </main>
  );
}
