/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5aquAsar05B
 */

import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";

export function BillHistory() {
  return (
    <div className="flex flex-col w-full min-h-screen pb-8">
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-xl md:text-2xl">
                হিসাবের ইতিহাস
              </CardTitle>
              {/* <UsersIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" /> */}
        </CardHeader>
        <div>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">Loan ID</TableHead>
                <TableHead>Borrower</TableHead>
                <TableHead>Amount</TableHead>
                <TableHead>Interest Rate</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Due Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">LN001</TableCell>
                <TableCell>John Doe</TableCell>
                <TableCell>$10,000</TableCell>
                <TableCell>5%</TableCell>
                <TableCell>Active</TableCell>
                <TableCell className="text-right">2024/01/01</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">LN002</TableCell>
                <TableCell>Jane Doe</TableCell>
                <TableCell>$20,000</TableCell>
                <TableCell>4.5%</TableCell>
                <TableCell>Paid</TableCell>
                <TableCell className="text-right">2023/12/01</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">LN003</TableCell>
                <TableCell>Michael Smith</TableCell>
                <TableCell>$15,000</TableCell>
                <TableCell>6%</TableCell>
                <TableCell>Active</TableCell>
                <TableCell className="text-right">2024/02/01</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </main>
    </div>
  );
}
